sudo: false
branches:
  only:
  - master
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_efc81948d3a6_key -iv $encrypted_efc81948d3a6_iv -in publish-key.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git remote set-url origin git@github.com:pythonbrasil/pythonbrasil12-site.git
- git fetch origin -f master:master
#install:
#- pip install --upgrade pip
#- pip install -r requirements.txt
#add the rest of setup here
#script:
#- make github
